export const SEND_MESSAGE = 'CHAT@SEND_MESSAGE'
export const DELETE_MESSAGE = 'CHAT@DELETE_MESSAGE'
export const INPUT_ADD_CHARACTER = 'CHAT@INPUT_ADD_CHARACTER'
export const OPEN_CHAT = 'CHAT@OPEN_CHAT'
